Repository Prography-9th-3team/packit-web, pull requests merged in 2024-05, with the labels that each got.

#19 Feat/common icon
  .storybook/main.ts
  next.config.js
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Icon/lib/check_indeterminate.svg
  src/components/common/Icon/lib/check_off.svg
  src/components/common/Icon/lib/check_on.svg
  src/components/common/Icon/lib/chevron_down.svg
  src/components/common/Icon/lib/home_04.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/placeholder.svg
  src/components/common/Icon/lib/plus.svg
  src/components/common/Icon/lib/search_sm.svg
  src/components/common/Icon/lib/warning_triangle.svg
  src/components/common/Icon/lib/x_close.svg
Labels: ✨ feat, 🎨 style

#18 Feat/Toast 컴포넌트 작업
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/index.tsx
  src/components/common/Toast/modules/ToastStateContext.tsx
  src/components/common/Toast/ui/ToastButton.tsx
  src/components/common/Toast/ui/ToastIcon.tsx
  src/components/common/Toast/ui/ToastLabel.tsx
  src/components/common/Toast/ui/ToastMain.tsx
  styles/theme/colors.ts
Labels: ✨ feat, 🎨 style

#20 Feat/common Avatar
  src/components/common/Avatar/Avatar.stories.tsx
  src/components/common/Avatar/constants.ts
  src/components/common/Avatar/index.tsx
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/user.svg
Labels: ✨ feat, 🎨 style

#22 Feat/common Tag 컴포넌트
  src/components/common/Tag/Tag.stories.tsx
  src/components/common/Tag/index.tsx
  src/components/common/Tag/modules/TagStateContext.tsx
  src/components/common/Tag/ui/TagLabel.tsx
  src/components/common/Tag/ui/TagMain.tsx
Labels: ✨ feat, 🎨 style

#24 Feat/Checkbox 컴포넌트 작업
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/common/Check/Check.stories.tsx
  src/components/common/Check/index.tsx
Labels: ✨ feat, 🎨 style

#33 Feat/ 스토리북 아이콘 갤러리 작업
  src/components/common/Avatar/index.tsx
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Icon/lib/check_indeterminate.svg
  src/components/common/Icon/lib/check_off.svg
  src/components/common/Icon/lib/check_on.svg
  src/components/common/Icon/lib/chevron_down.svg
  src/components/common/Icon/lib/home_04.svg
  src/components/common/Icon/lib/placeholder.svg
  src/components/common/Icon/lib/plus.svg
  src/components/common/Icon/lib/search_sm.svg
  src/components/common/Icon/lib/user.svg
  src/components/common/Icon/lib/warning_triangle.svg
  src/components/common/Icon/lib/x_close.svg
  src/components/common/Tag/Tag.stories.tsx
  src/stories/Colors.mdx
  src/stories/IconGallery.mdx
Labels: ✅ test, 🎨 style

#36 Feat: Menu 컴포넌트 작업
  src/components/common/Icon/index.tsx
  src/components/common/Icon/lib/bell_s.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Menu/Menu.stories.tsx
  src/components/common/Menu/index.ts
  src/components/common/Menu/module/MenuStateContext.tsx
  src/components/common/Menu/ui/MenuLabel.tsx
  src/components/common/Menu/ui/MenuMain.tsx
Labels: ✨ feat, 🎨 style

#37 Feat: Rank Menu 컴포넌트 작업
  src/components/common/Icon/lib/bookmark_add.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/link_03.svg
  src/components/common/RankMenu/RankMenu.stories.tsx
  src/components/common/RankMenu/index.tsx
Labels: ✨ feat, 🎨 style

#43 Style/디자인 공통 컴포넌트 QA 수정 & 사이드바 컴포넌트 작업
  public/logo.svg
  src/app/layout.tsx
  src/components/Sidebar/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/modules/ButtonStateContext.tsx
  src/components/common/Button/ui/ButtonLabel.tsx
  src/components/common/Button/ui/ButtonMain.tsx
  src/components/common/Divider/index.tsx
  src/components/common/Icon/lib/chevron-left-double.svg
  src/components/common/Icon/lib/chevron-right-double.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/logout.svg
  src/components/common/Icon/lib/mail.svg
  src/components/common/Icon/lib/setting.svg
  src/components/common/Menu/ui/MenuMain.tsx
  src/components/common/Option/Option.stories.tsx
  src/components/common/Select/ui/SelectInputWrapper.tsx
  src/components/common/Spinner/Index.tsx
  src/components/common/Spinner/Spinner.stories.tsx
  src/components/common/Spinner/constants.ts
  tailwind.config.ts
Labels: ✨ feat, 🐛 fix, 🎨 style
