Repository Prography-9th-3team/packit-web, pull requests merged in 2024-06, with the labels that each got.

#50 Fear/vercel deploy 설정
  src/app/oauth2/redirect/page.tsx
  vercel.json
Labels: 🔧 chore

#49 Feat/공통 모달 스토어 및 북마크 모달 추가
  .storybook/preview.tsx
  src/app/layout.tsx
  src/app/oauth2/redirect/page.tsx
  src/app/page.tsx
  src/components/Sidebar/index.tsx
  src/components/common/Button/modules/ButtonStateContext.tsx
  src/components/common/Icon/lib/file_plus.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/ModalLayout.tsx
  src/components/common/Modal/ModalPortal.tsx
  src/components/common/Modal/ui/BookmarkModal.tsx
  src/hooks/useDragUpload.ts
  src/stores/modalStore.ts
Labels: ✨ feat, 🎨 style

#53 Feat/메인 홈 페이지 작업
  src/app/page.tsx
  src/components/ContentBox/index.tsx
  src/components/FilterBox/index.tsx
  src/components/TabList/index.tsx
  src/components/common/Button/ui/ButtonLabel.tsx
  src/components/common/Button/ui/ButtonMain.tsx
  src/components/common/Icon/lib/bookmark_add.svg
  src/components/common/Icon/lib/check_circle.svg
  src/components/common/Icon/lib/grid.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/list.svg
  src/components/common/Icon/lib/plus_circle.svg
  src/hooks/useQueyString.ts
Labels: ✨ feat, 🎨 style

#54 Feat/북마크 목록 API 연동
  next.config.js
  package.json
  pnpm-lock.yaml
  public/assets/image/empty_image.png
  src/apis/api.ts
  src/apis/auth.ts
  src/apis/bookmark.ts
  src/apis/index.ts
  src/app/Provider.tsx
  src/app/api/auth/cookie/route.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/oauth2/redirect/page.tsx
  src/components/BookmarkCard/index.tsx
  src/components/ContentBox/index.tsx
  src/components/Footer/index.tsx
  src/components/Sidebar/index.tsx
  src/components/TabList/index.tsx
  src/components/common/Modal/ModalLayout.tsx
  src/lib/utils.ts
  src/stores/authStore.ts
Labels: ✨ feat

#55 Fix/mix content issuse로 proxy 적용
  next.config.js
  src/apis/index.ts
Labels: 🐛 fix

#57 Feat/home page
  next.config.js
  package.json
  pnpm-lock.yaml
  src/apis/api.ts
  src/apis/bookmark.ts
  src/apis/category.ts
  src/apis/index.ts
  src/app/api/meta/route.tsx
  src/app/onboarding/components/PackitTooltip.tsx
  src/app/page.tsx
  src/components/BookmarkCard/index.tsx
  src/components/ContentBox/index.tsx
  src/components/FilterBox/index.tsx
  src/components/Sidebar/index.tsx
  src/components/TabList/index.tsx
  src/components/common/Icon/lib/dots_vertical.svg
  src/components/common/Icon/lib/heart.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Modal/ModalLayout.tsx
  src/components/common/Modal/ui/BookmarkModal.tsx
  src/components/common/Textfield/module/TextfieldStateContext.tsx
  src/components/common/Textfield/ui/TextfieldInput.tsx
  src/components/common/Textfield/ui/TextfieldMain.tsx
  src/hooks/useDragUpload.ts
  src/lib/meta.ts
Labels: ✨ feat, 🙋🏻 review, 🎨 style

#62 Feat/온보딩 페이지 퍼블리싱 작업
  package.json
  pnpm-lock.yaml
  public/assets/image/onboarding_step_one.png
  public/assets/image/onboarding_step_three.png
  public/assets/image/onboarding_step_two.png
  src/app/onboarding/page.tsx
  src/components/Footer/index.tsx
  src/components/PackitTooltip/index.tsx
  src/components/Sidebar/index.tsx
Labels: ✨ feat, 🎨 style
